import React, { useEffect, useState, useContext } from "react";
import {
  Box,
  Typography,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Container,
} from "@mui/material";
import { AppContent } from "../context/AppContext";
import qcLogo from "../assets/qc-logo.png";
import qcdeLogo from "../assets/qcde-logo.png";
import TrafficChart from "./TrafficChart";
import AccomplishmentChart from "./AccomplishmentChart";
import SatisfactionCard from "../components/SatisfactionCard";
import Button from "@mui/material/Button";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const statusColors = {
  Submitted: "#0288d1",
  Accepted: "#1976d2",
  "In-progress": "#fbc02d",
  Completed: "#388e3c",
  Rejected: "#d32f2f",
};

function DashboardHome() {
  const [counts, setCounts] = useState({});
  const [recentReports, setRecentReports] = useState([]);
  const [totalDupaCost, setTotalDupaCost] = useState(0);
  const [loading, setLoading] = useState(true);
  const [averageRatings, setAverageRatings] = useState({
    avgOverall: 0,
    avgService: 0,
    avgSpeed: 0,
  });

  // Fetch export generated by
  const { userData } = useContext(AppContent);
  const preparedBy = [
    userData?.firstName,
    userData?.middleName,
    userData?.surname,
    userData?.suffix,
  ]
    .filter((p) => p && String(p).trim())
    .join(" ");

  // Fetch report data
  const fetchOverviewData = async () => {
    try {
      const reportsResponse = await fetch(
        import.meta.env.VITE_BACKEND_URL + "/api/reports/list-all",
        { credentials: "include" }
      );
      const reportsData = await reportsResponse.json();

      if (reportsData.success) {
        const statusCounts = reportsData.reports.reduce((acc, r) => {
          acc[r.status] = (acc[r.status] || 0) + 1;
          return acc;
        }, {});
        setCounts(statusCounts);

        const sortedReports = [...reportsData.reports].sort(
          (a, b) => new Date(b.timestamp) - new Date(a.timestamp)
        );
        setRecentReports(sortedReports.slice(0, 5));
      }
    } catch (err) {
      console.error("Failed to fetch reports:", err);
    }
  };

  const fetchDupaCosting = async () => {
    try {
      const res = await fetch(
        import.meta.env.VITE_BACKEND_URL + "/api/reports/total-cost",
        { credentials: "include" }
      );
      const data = await res.json();
      if (data.success) {
        setTotalDupaCost(data.totalCost);
      }
    } catch (err) {
      console.error("Failed to fetch DUPA costing:", err);
    }
  };

  const fetchAverageRatings = async () => {
    try {
      const res = await fetch(
        import.meta.env.VITE_BACKEND_URL + "/api/feedback/averages",
        { credentials: "include" }
      );
      const data = await res.json();
      if (data.success) {
        setAverageRatings(data.averages);
      }
    } catch (err) {
      console.error("Failed to fetch average ratings:", err);
    }
  };

  useEffect(() => {
    (async () => {
      setLoading(true);
      await Promise.all([
        fetchOverviewData(),
        fetchDupaCosting(),
        fetchAverageRatings(),
      ]);
      setLoading(false);
    })();
  }, []);

  const statuses = [
    "Submitted",
    "Accepted",
    "In-progress",
    "Completed",
    "Rejected",
  ];

  // Export report summary function and logic
  // Load the QCDE header
  const loadImageAsDataURL = (src) =>
    new Promise((resolve, reject) => {
      const img = new Image();
      img.src = src;
      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;

        const ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0);

        resolve(canvas.toDataURL("image/png"));
      };
      img.onerror = reject;
    });

  const handleExportDashboardPDF = async () => {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    let leftLogo = null;
    let rightLogo = null;

    try {
      leftLogo = await loadImageAsDataURL(qcLogo);
    } catch (error) {
      console.error("Left logo failed to load:", error);
    }

    try {
      rightLogo = await loadImageAsDataURL(qcdeLogo);
    } catch (error) {
      console.error("Right logo failed to load:", error);
    }

    const drawHeader = () => {
      if (leftLogo) doc.addImage(leftLogo, "PNG", 10, 8, 22, 22);
      if (rightLogo) doc.addImage(rightLogo, "PNG", pageWidth - 32, 8, 22, 22);

      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text("QUEZON CITY DEPARTMENT OF ENGINEERING", pageWidth / 2, 12, {
        align: "center",
      });

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(
        "5th, 6th, 7th, and 8th Floors, Civic Center Bldg. B, Quezon City Hall Compound, Barangay Central, Diliman, Quezon City",
        pageWidth / 2,
        18,
        { align: "center" }
      );
      doc.text("8988-4242 locals 8658, 8659, 8538", pageWidth / 2, 23, {
        align: "center",
      });
      doc.text("engineering@quezoncity.gov.ph", pageWidth / 2, 28, {
        align: "center",
      });

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text("DASHBOARD SUMMARY REPORT", pageWidth / 2, 36, {
        align: "center",
      });

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(`Prepared by: ${preparedBy || "N/A"}`, 10, 42);
      doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth - 10, 42, {
        align: "right",
      });

      doc.line(10, 45, pageWidth - 10, 45);
    };

    const didDrawPage = () => {
      drawHeader();

      const pageNumber = doc.getCurrentPageInfo().pageNumber;
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(`Page ${pageNumber}`, pageWidth - 10, pageHeight - 6, {
        align: "right",
      });
    };

    const sectionTitle = (title, y) => {
      doc.setFillColor(238, 241, 250);
      doc.roundedRect(10, y - 5, pageWidth - 20, 8, 1.5, 1.5, "F");

      doc.setTextColor(38, 48, 146);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(title, 13, y);

      doc.setTextColor(0, 0, 0);
    };

    // Report Status Summary Section
    let y = 54;

    sectionTitle("Report Status Summary", y);

    const statusData = statuses.map((status) => ({
      label: status,
      value: counts[status] || 0,
      color:
        status === "Submitted"
          ? [2, 136, 209]
          : status === "Accepted"
          ? [25, 118, 210]
          : status === "In-progress"
          ? [251, 192, 45]
          : status === "Completed"
          ? [56, 142, 60]
          : [211, 47, 47],
    }));

    const totalReports = statusData.reduce((sum, item) => sum + item.value, 0);
    const maxValue = Math.max(...statusData.map((item) => item.value), 1);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Reports: ${totalReports}`, 13, y + 12);

    let graphY = y + 20;

    statusData.forEach((item) => {
      const barWidth = (item.value / maxValue) * 105;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(0, 0, 0);
      doc.text(item.label, 13, graphY + 4);

      doc.setFillColor(235, 235, 235);
      doc.roundedRect(55, graphY, 105, 6, 1, 1, "F");

      doc.setFillColor(...item.color);
      doc.roundedRect(55, graphY, barWidth, 6, 1, 1, "F");

      doc.setFont("helvetica", "bold");
      doc.text(String(item.value), 166, graphY + 4);

      graphY += 11;
    });

    y = graphY + 8;

    // Financial and Satisfaction Summary Section
    sectionTitle("Financial and Satisfaction Summary", y);

    autoTable(doc, {
      startY: y + 6,
      body: [
        [
          "Total DUPA Costing",
          `PHP ${Number(totalDupaCost || 0).toLocaleString(undefined, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          })}`,
        ],
        [
          "Average Overall Rating",
          `${averageRatings.avgOverall?.toFixed?.(2) || "0.00"} / 5.00`,
        ],
        [
          "Average Service Rating",
          `${averageRatings.avgService?.toFixed?.(2) || "0.00"} / 5.00`,
        ],
        [
          "Average Speed Rating",
          `${averageRatings.avgSpeed?.toFixed?.(2) || "0.00"} / 5.00`,
        ],
      ],
      theme: "grid",
      margin: { top: 50, left: 10, right: 10, bottom: 15 },
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      columnStyles: {
        0: {
          fontStyle: "bold",
          fillColor: [245, 245, 245],
          cellWidth: 80,
        },
        1: {
          halign: "right",
          fontStyle: "bold",
        },
      },
      didDrawPage,
    });

    // Recent Reports Section
    y = doc.lastAutoTable.finalY + 12;

    sectionTitle("Recent Reports", y);

    autoTable(doc, {
      startY: y + 6,
      head: [
        [
          "Report No.",
          "Classification",
          "Measurement",
          "Status",
          "Location",
          "Date",
        ],
      ],
      body: recentReports.map((r) => [
        r.reportNumber || "N/A",
        r.classification || "N/A",
        r.measurement || "N/A",
        r.status || "N/A",
        r.location || "N/A",
        r.timestamp ? new Date(r.timestamp).toLocaleString() : "N/A",
      ]),
      theme: "grid",
      margin: { top: 50, left: 10, right: 10, bottom: 15 },
      styles: {
        fontSize: 8,
        cellPadding: 2.5,
        overflow: "linebreak",
        valign: "middle",
      },
      headStyles: {
        fillColor: [38, 48, 146],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: [248, 249, 252],
      },
      didDrawPage,
    });

    doc.save("dashboard-summary-report.pdf");
  };

  return (
    <Container maxWidth="xl" sx={{ py: 4 }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h5" fontWeight={600}>
          Dashboard Overview
        </Typography>

        <Button
          variant="contained"
          startIcon={<PictureAsPdfIcon />}
          onClick={handleExportDashboardPDF}
          disabled={loading}
        >
          Export Summary
        </Button>
      </Box>

      {/* Status Summary Cards */}
      <Box
        mb={4}
        sx={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "space-between",
          gap: 2,
        }}
      >
        {statuses.map((status) => (
          <Card
            key={status}
            sx={{
              flex: "1 1 calc(20% - 16px)",
              minWidth: 150,
              borderLeft: `5px solid ${statusColors[status]}`,
            }}
          >
            <CardContent>
              <Typography
                variant="subtitle2"
                fontWeight={600}
                color="text.secondary"
              >
                {status}
              </Typography>
              <Typography variant="h5" fontWeight={700}>
                {loading ? <CircularProgress size={20} /> : counts[status] || 0}
              </Typography>
            </CardContent>
          </Card>
        ))}
      </Box>

      {/* Main + Sidebar */}
      <Box
        sx={{
          display: "flex",
          flexDirection: { xs: "column", lg: "row" },
          gap: 2,
        }}
      >
        {/* Left: Charts stacked */}
        <Box
          sx={{
            flex: 1,
            display: "flex",
            flexDirection: "column",
            gap: 2,
          }}
        >
          <Card sx={{ width: "100%" }}>
            <CardContent sx={{ p: 1 }}>
              <TrafficChart />
            </CardContent>
          </Card>
          <Card sx={{ width: "100%" }}>
            <CardContent sx={{ p: 1 }}>
              <AccomplishmentChart />
            </CardContent>
          </Card>
        </Box>

        {/* Right: Sidebar */}
        <Box sx={{ flex: { xs: "1 1 100%", lg: "0 0 320px" } }}>
          {/* Total DUPA Costing Card */}
          <Card sx={{ mb: 2 }}>
            <CardContent>
              <Typography variant="subtitle2" color="text.secondary">
                Total DUPA Costing
              </Typography>
              <Typography variant="h4" fontWeight={700}>
                {loading ? (
                  <CircularProgress size={24} />
                ) : (
                  `₱${totalDupaCost.toLocaleString()}`
                )}
              </Typography>
            </CardContent>
          </Card>

          {/* Feedback Summary */}
          <SatisfactionCard averageRatings={averageRatings} loading={loading} />

          {/* Recent Reports */}
          <Typography variant="h6" fontWeight={600} mb={2}>
            Recent Reports
          </Typography>
          {loading ? (
            <CircularProgress />
          ) : (
            <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
              {recentReports.map((r) => (
                <Card key={r.reportNumber}>
                  <CardContent>
                    <Box display="flex" justifyContent="space-between" mb={1}>
                      <Typography variant="subtitle2" fontWeight={600}>
                        {r.classification} - {r.measurement || "N/A"}
                      </Typography>
                      <Chip
                        label={r.status}
                        size="small"
                        sx={{
                          bgcolor: statusColors[r.status] || "grey",
                          color: "white",
                          fontWeight: 500,
                          textTransform: "capitalize",
                        }}
                      />
                    </Box>
                    <Typography variant="body2" gutterBottom>
                      {r.description}
                    </Typography>
                    <Typography
                      variant="caption"
                      color="text.secondary"
                      component="div"
                      sx={{ marginBottom: 1 }}
                    >
                      {r.location && (
                        <>
                          <strong>Location:</strong> {r.location}
                        </>
                      )}
                    </Typography>
                    <Typography
                      variant="caption"
                      color="text.secondary"
                      component="div"
                    >
                      {new Date(r.timestamp).toLocaleString()}
                    </Typography>
                  </CardContent>
                </Card>
              ))}
            </Box>
          )}
        </Box>
      </Box>
    </Container>
  );
}

export default DashboardHome;
